#!/usr/bin/env python3
"""Generate llama-hugs config.yaml from production config with:
- all model IDs prefixed "hugs-"
- capabilities.tools = true on audited tool-capable models
- groups rewritten with prefixed members, same GPU structure
- own apiKeys + store path

Read-only against /etc/llama-swap/config.yaml.
"""
import re
import sys

import yaml

SRC = "/etc/llama-swap/config.yaml"
DST = "/opt/llama-hugs/config.yaml"
AUDIT = "/home/rahlquist/llama-hugs/f1/tools-audit.md"

# Tool-capable base names (from tools-audit.md). Matched as prefix of the
# entry id before quant suffixes; -cuda aliases inherit.
TOOL_BASES = [
    "qwen3-8-27b", "dagger-qwen3-6-27b", "dirk-qwen3-8-27b",
    "nail-qwen3-6-35b-a3b", "qwen3-6-35b-a3b",
    "qwen3-6-27b-fable-fus-711", "qwen3-30b-a3b-instruct-2507",
    "qwen-qwen3-30b-a3b-instruct-2507", "qwen3-coder-30b-a3b",
    "qwen3-30b-a3b", "qwen3.5-9b", "ling-mini-2",
    "glm-4-7-flash", "mistral-7b", "qwen2.5-coder-14b",
]

def tool_capable(entry_id: str) -> bool:
    for base in TOOL_BASES:
        if entry_id == base or entry_id.startswith(base):
            return True
    return False

with open(SRC) as f:
    prod = yaml.safe_load(f)

out_models = {}
for mid, mc in (prod.get("models") or {}).items():
    entry = dict(mc)
    caps = dict(entry.get("capabilities") or {})
    caps["tools"] = tool_capable(mid)
    if not caps["tools"]:
        caps.pop("tools")  # keep absent rather than false, matching audit
    entry["capabilities"] = caps
    out_models["hugs-" + mid] = entry

out_groups = {}
for gname, grp in (prod.get("groups") or {}).items():
    members = ["hugs-" + m for m in (grp.get("members") or []) if ("hugs-" + m) in out_models]
    ng = dict(grp)
    ng["members"] = members
    out_groups[gname] = ng

# Aliases: every model also answers to its unprefixed production ID so clients
# migrated from :8080 keep working without reconfiguration.
for mid, entry in list(out_models.items()):
    unprefixed = mid[5:] if mid.startswith("hugs-") else mid
    if unprefixed != mid and unprefixed not in out_models:
        entry.setdefault("aliases", []).append(unprefixed)

header = """# llama-hugs config.yaml — wimpy PRIMARY router (since port swap 2026-08-24)
# GENERATED by f1/gen-config.py from /etc/llama-swap/config.yaml — do not hand-edit
# model entries. Regenerate after production fleet changes.
#
# Divergence from production: tools flags per f1/tools-audit.md, own store path,
# NO apiKeys (behavioral parity with llama-swap's keyless :8080 — see plan note).
# Same GGUF paths. Unprefixed IDs kept as aliases for client compatibility.

"""

out = {
    "healthCheckTimeout": prod.get("healthCheckTimeout", 180),
    "groups": out_groups,
    "models": out_models,
    "store": {"path": "/opt/llama-hugs/hugs.sqlite"},
}

with open(DST, "w") as f:
    f.write(header)
    yaml.safe_dump(out, f, sort_keys=False, default_flow_style=False, width=1000)

tooled = sum(1 for m in out_models.values() if (m.get("capabilities") or {}).get("tools"))
print(f"wrote {DST}: {len(out_models)} models, {tooled} with tools=true")
